version: '3'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test_password
  dodo:
    image: dodo
    environment:
      MongoDBServerURL: mongodb://root:test_password@localhost:27017/?authSource=admin
    volumes:
      - type: bind
        source: ./DodoServer_config.json
        target: /home/DodoServer_config.json
    ports:
      - "5000:5001"
    depends_on:
      - mongo