version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vLS6piEC
  dodo:
    image: dodo
    environment:
      MongoDBServerURL: "mongodb://root:vLS6piEC@dodo_mongo_1:27017/?authSource=admin"
      ASPNETCORE_Kestrel__Certificates__Default__Password: "YsS8k8oe"
      ASPNETCORE_Kestrel__Certificates__Default__Path: "/https/dodo.pfx"
    volumes:
      - type: "bind"
        source: "./DodoServer_config.json"
        target: "/DodoServer_config.json"
    ports:
      - "5000:5001"
    depends_on:
      - mongo
