version: '3.2'
services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: vLS6piEC
  dodo:
    image: dodo
    environment:
      MongoDBServerURL: "mongodb://root:vLS6piEC@dodo_mongo_1:27017/?authSource=admin"
      REACT_APP_ROOT_URL: "http://localhost:22957/"
      ASPNETCORE_URLS: "http://localhost:22957"
      ReactPath: "/wwwroot/"
    volumes:
      - type: "bind"
        source: "./DodoServer_config.json"
        target: "/DodoServer_config.json"
    ports:
      - "22957:22957"
    depends_on:
      - mongo
